### ISSUE TITLE
Prompt text doesn't contrast well

### ISSUE THREAD

**Issue by ninnypants** [10up/Derrick-CLI#1]
When running `derrick create` the prompt text disappears into the terminal background making it hard to know what you should be entering.

![screenshot_on_2015-04-30_at_14_53_25](https://cloud.githubusercontent.com/assets/408862/7423017/11246f54-ef4f-11e4-933c-539a07b9e9b9.png)

**Comment by morganestes** [comment]
@ninnypants What color scheme are you using? It's visible with Solarized Dark for me, but definitely could be easier to read.
![screencapture at thu apr 30 16 52 30 mdt 2015](https://cloud.githubusercontent.com/assets/110755/7424008/6bf3f760-ef59-11e4-8628-6012547b8602.png)

**Comment by ericmann** [comment]
What color scheme and what Console app? This is a slightly different UI that I've seen with either Windows or Mac.

**Comment by ninnypants** [comment]
[This is my setup.](https://github.com/robbyrussell/oh-my-zsh/wiki/themes#agnoster) Agnoster, zsh, Solarized Dark, and iTerm2. Going in and manually tweaking the contrast levels in my profile seems to clear it up, so it's probably a difference between the terminal app and iterm handle colors.
