### ISSUE TITLE
Can't create a project with a space in the name

### ISSUE THREAD

**Issue by morganestes** [10up/Derrick-CLI#3]
The prompt tells me that I can use "letters, spaces, and dashes" but rejects my project name when it has spaces in it.

``` console
$ derrick create
info:    This utility will assist you in creating a new project in Derrick with a corresponding manifest.json file.
prompt: Name (letters, spaces, and dashes):  University of Maine
error:   Invalid input for Name (letters, spaces, and dashes)
prompt: Name (letters, spaces, and dashes):  University of Maine
error:   Invalid input for Name (letters, spaces, and dashes)
prompt: Na
```

**Comment by sc0ttkclark** [comment]
Stems from https://github.com/10up/Derrick-CLI/blob/master/lib/commands/create.js#L51

Sounds like we don't want to support spaces for the names if we're using them for the folder names.

**Comment by tlovett1** [comment]
We don't want spaces in names.
