### ISSUE TITLE
WP passthru command needs to filter out path used to find Derrick project

### ISSUE THREAD

**Issue by johnpbloch** [10up/Derrick-CLI#7]
When running `wp` passthru commands, we're using `--path` to indicate to Derrick which project in which to run the command. It looks like we're passing that flag into the wp command itself, which is making it try to run the wp command against an installation that doesn't exist.

**Comment by tlovett1** [comment]
What if you wanted to specify a different path for the wp and derrick commands? It might make sense to rename `path` to `project-path`

**Comment by johnpbloch** [comment]
That's fine, but the user shouldn't ever need to specify a WP `--path`. It will always live in `/var/www/html` insided the `<project>-php` docker container.

**Comment by johnpbloch** [comment]
To clarify my thoughts, it probably is a good idea to change the name of `--path` to `--project-path`. Even though there isn't much need for the path flag for the wp command inside derrick, it would be helpful for users to understand that they need to supply `--project-path` for *Derrick's` sake, not for WP CLI's.
